### ISSUE TITLE
Tailscale

### ISSUE THREAD

**Issue by tully-8888** [williampiat3/ImprovingPSRemotePlay#6]
Hello, can you take a look at Tailscale? I think that would be much easier to configure.

**Comment by williampiat3** [comment]
We recently came aware of the existence of tailscale and we are planning to add it to our benchmarks yet in its simplest form tailscale relies on an external server (very much like PSremotePlay relies on Sony's server). Our proposed solution allows to bypass any intermediate. This is why an immediate comparison is not feasible,yet we are investigating further if it can be tuned in a way to make PSremotePlay work.

**Comment by tully-8888** [comment]
Thanks for the answer!

**Comment by Pimss** [comment]
@badbanii, we have added an [installation guide](https://github.com/williampiat3/ImprovingPSRemotePlay/blob/main/tailscale_install.md) and performances tests for Tailscale.  Short answer, it is simpler and give a solution for locked routers but as @williampiat3 mention, it relies on an external server and is not very adapted in our use case to pi zero hardware due to the additional computational power needed (from our limited testing abilities)
